name: Run R script

on:
  push:
    branches:
      - actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'options(repos = "https://packagemanager.rstudio.com/cran/latest")'
          Rscript -e 'install.packages(c("tidyverse", "tidymodels", "vip"))'

      - name: Run script
        run: Rscript -e 'source("script.R")'
